export const seed = {
  tenant: {
    id: "T-ACME",
    name: "华东制造集团",
    plan: "Enterprise",
    plants: 3,
    lines: 17,
    users: 428,
  },
  currentUser: {
    id: "U-1001",
    name: "林计划",
    role: "计划员",
    permissions: ["orders:write", "schedule:write", "quality:write", "inventory:write", "config:read"],
  },
  users: [
    {
      id: "U-1001",
      name: "林计划",
      email: "lin.plan@huadong.example",
      role: "计划员",
      roleKey: "planner",
      department: "供应链计划部",
      title: "高级计划员",
      plant: "华东一厂",
      status: "在线",
      lastActive: "刚刚",
      permissions: ["orders:write", "schedule:write", "quality:write", "inventory:write", "config:read"],
    },
    {
      id: "U-1002",
      name: "周总",
      email: "zhou.coo@huadong.example",
      role: "COO / 工厂总经理",
      roleKey: "coo",
      department: "集团制造运营",
      title: "集团制造负责人",
      plant: "集团",
      status: "在线",
      lastActive: "2 分钟前",
      permissions: ["dashboard:read", "kanban:write", "approval:write", "audit:read"],
    },
    {
      id: "U-1003",
      name: "陈班长",
      email: "chen.shop@huadong.example",
      role: "生产主管 / 班组长",
      roleKey: "production",
      department: "包装车间",
      title: "包装二线班组长",
      plant: "华东一厂",
      status: "在线",
      lastActive: "刚刚",
      permissions: ["execution:write", "mobile:write", "routes:read"],
    },
    {
      id: "U-1004",
      name: "吴质检",
      email: "wu.qa@huadong.example",
      role: "质量经理 / 质检员",
      roleKey: "quality",
      department: "质量管理部",
      title: "QA 经理",
      plant: "华东一厂",
      status: "离线",
      lastActive: "18 分钟前",
      permissions: ["quality:write", "workflow:write", "audit:read"],
    },
    {
      id: "U-1005",
      name: "何仓储",
      email: "he.wh@huadong.example",
      role: "仓库 / 物料员",
      roleKey: "warehouse",
      department: "仓储物流部",
      title: "仓储主管",
      plant: "中央仓",
      status: "在线",
      lastActive: "5 分钟前",
      permissions: ["inventory:write", "mobile:write", "integrations:read"],
    },
    {
      id: "U-1006",
      name: "许 IT",
      email: "xu.it@huadong.example",
      role: "IT / 实施顾问",
      roleKey: "it",
      department: "信息化中心",
      title: "实施负责人",
      plant: "集团",
      status: "在线",
      lastActive: "刚刚",
      permissions: ["config:write", "integrations:write", "audit:read", "users:read"],
    },
  ],
  commercialPackages: [
    {
      id: "PKG-STARTER",
      name: "Starter 首厂试点",
      target: "单工厂 / 1-3 条产线",
      priceModel: "平台费 + 现场轻量席位 + 标准实施包",
      scope: "MES、QMS、WMS、移动扫码、基础看板",
      implementation: "4 周样板线启动，8 周首厂验收",
      roi: "纸单减少 70%，报工及时率提升 35%",
      status: "可售",
      modules: ["生产执行", "移动现场", "质量闭环", "物料库存", "看板中心"],
    },
    {
      id: "PKG-PRO",
      name: "Professional 多产线协同",
      target: "多产线 / 多车间 / 已有 ERP",
      priceModel: "按模块 + 产线 + API 调用量",
      scope: "APS/MRP、工艺路线、流程引擎、开放集成、数据智能",
      implementation: "6-10 周跑通计划、物料、生产、质量闭环",
      roi: "计划响应提速 50%，缺料停线风险降低 40%",
      status: "主推",
      modules: ["订单排程", "主计划 MRP", "工艺路线", "流程引擎", "开放集成", "数据智能"],
    },
    {
      id: "PKG-ENTERPRISE",
      name: "Enterprise 集团运营",
      target: "多工厂集团 / 供应链协同",
      priceModel: "集团协议 + 专属 SLA + 行业包",
      scope: "多工厂运营、成本财务、供应商、设备 IoT、工业智能体",
      implementation: "首厂复制模板，12-20 周扩展多工厂",
      roi: "库存周转提升 15-25%，集团准交预测统一",
      status: "可售",
      modules: ["成本财务", "采购供应商", "设备资源", "工业智能体", "实施蓝图"],
    },
  ],
  salesOpportunities: [
    {
      id: "OP-1001",
      packageId: "PKG-PRO",
      customer: "华东制造集团",
      owner: "售前顾问",
      stage: "ROI 诊断",
      nextStep: "导入真实订单、库存和质量样本，生成样板线价值测算。",
      status: "进行中",
    },
  ],
  activationTasks: [
    {
      id: "ACT-COO",
      role: "COO / 工厂总经理",
      owner: "客户成功经理",
      workspace: "总览工作台 + 看板中心",
      firstAction: "确认首厂准交、库存、质量和产线负载四个验收指标。",
      successMetric: "每日查看经营风险，周会使用同一套指标复盘。",
      status: "进行中",
    },
    {
      id: "ACT-PLAN",
      role: "计划员",
      owner: "实施顾问",
      workspace: "订单排程 + 主计划 MRP",
      firstAction: "导入真实订单池，处理缺料和产能例外，冻结试点线计划。",
      successMetric: "计划变更响应时间下降，齐套风险可提前识别。",
      status: "待启动",
    },
    {
      id: "ACT-SHOP",
      role: "班组长 / 现场员工",
      owner: "生产主管",
      workspace: "移动现场 + 生产执行",
      firstAction: "扫码工单完成一次报工，并把异常回写到事件流。",
      successMetric: "报工及时率提升，现场不再依赖纸单汇总。",
      status: "待启动",
    },
    {
      id: "ACT-QA",
      role: "质检员 / QA",
      owner: "质量经理",
      workspace: "质量闭环 + 流程引擎",
      firstAction: "执行首检/巡检，关闭一条偏差并归档批次追溯链。",
      successMetric: "偏差关闭时长下降，追溯链完整可复核。",
      status: "待启动",
    },
    {
      id: "ACT-IT",
      role: "IT / 实施顾问",
      owner: "IT 负责人",
      workspace: "开放集成 + 配置模板 + 审计日志",
      firstAction: "完成 ERP/PLM/WMS 接口联调、角色权限和审计抽查。",
      successMetric: "接口同步成功率稳定，权限和审计满足上线要求。",
      status: "进行中",
    },
  ],
  masterDataChecks: [
    {
      id: "MD-MATERIAL",
      domain: "物料与安全库存",
      owner: "仓储主管",
      source: "ERP + WMS",
      readiness: 86,
      issues: 12,
      status: "待校验",
    },
    {
      id: "MD-BOM",
      domain: "BOM 与工艺路线",
      owner: "工艺工程",
      source: "PLM + Excel",
      readiness: 74,
      issues: 18,
      status: "待校验",
    },
    {
      id: "MD-ORG",
      domain: "组织、人员与权限",
      owner: "IT 负责人",
      source: "HR + 手工矩阵",
      readiness: 92,
      issues: 5,
      status: "待校验",
    },
    {
      id: "MD-LINE",
      domain: "产线、工位与设备",
      owner: "设备工程",
      source: "设备台账 + 现场盘点",
      readiness: 68,
      issues: 21,
      status: "待导入",
    },
    {
      id: "MD-QA",
      domain: "检验标准与质量规则",
      owner: "质量经理",
      source: "QMS + SOP",
      readiness: 81,
      issues: 9,
      status: "待校验",
    },
  ],
  lines: [
    { id: "L1", name: "灌装一线", plant: "华东一厂", status: "运行", oee: 86, load: 78 },
    { id: "L2", name: "包装二线", plant: "华东一厂", status: "待料", oee: 64, load: 52 },
    { id: "L3", name: "柔性三线", plant: "华东一厂", status: "运行", oee: 91, load: 45 },
    { id: "L4", name: "外协装配", plant: "华南二厂", status: "换线", oee: 72, load: 69 },
  ],
  processRoutes: [
    {
      id: "PR-1001",
      product: "果味饮料 330ml",
      version: "V3.4",
      line: "L1 / L3",
      owner: "工艺工程",
      cycleTime: "38 秒/箱",
      qrCode: "QR-PR-1001",
      status: "已发布",
      bom: [
        { id: "M-120", material: "食品级瓶坯", qty: "24", uom: "pcs/箱", scrap: "0.8%" },
        { id: "M-884", material: "铝塑包材", qty: "1", uom: "套/箱", scrap: "1.2%" },
        { id: "M-721", material: "果味浓缩液", qty: "7.8", uom: "L/批", scrap: "0.5%" },
      ],
      steps: [
        { sequence: 10, name: "瓶坯上线", station: "ST-101", equipment: "上瓶机", qualityGate: "扫码批次校验", sop: "SOP-FB-101", status: "已发布" },
        { sequence: 20, name: "灌装旋盖", station: "ST-108", equipment: "灌装旋盖机", qualityGate: "首件扭矩", sop: "SOP-FB-108", status: "已发布" },
        { sequence: 30, name: "贴标装箱", station: "ST-126", equipment: "高速贴标机", qualityGate: "标签偏移", sop: "SOP-FB-126", status: "已发布" },
      ],
    },
    {
      id: "PR-2007",
      product: "控制板 A7",
      version: "V1.9",
      line: "L3",
      owner: "电子工程",
      cycleTime: "9 分钟/片",
      qrCode: "QR-PR-2007",
      status: "变更中",
      bom: [
        { id: "M-774", material: "控制芯片", qty: "1", uom: "pcs", scrap: "0.3%" },
        { id: "M-775", material: "PCB 主板", qty: "1", uom: "pcs", scrap: "0.4%" },
        { id: "M-792", material: "测试治具", qty: "1", uom: "套/线", scrap: "0%" },
      ],
      steps: [
        { sequence: 10, name: "烧录", station: "ICT-01", equipment: "ICT 测试台", qualityGate: "SN 防重", sop: "SOP-EL-210", status: "已发布" },
        { sequence: 20, name: "功能测试", station: "ICT-02", equipment: "ICT 测试台", qualityGate: "测试结果回传", sop: "SOP-EL-220", status: "待发布" },
        { sequence: 30, name: "终检包装", station: "PK-03", equipment: "视觉工位", qualityGate: "外观抽检", sop: "SOP-EL-230", status: "待发布" },
      ],
    },
    {
      id: "PR-3003",
      product: "压装套件 P9",
      version: "V2.1",
      line: "L4",
      owner: "外协工程",
      cycleTime: "4.5 分钟/套",
      qrCode: "QR-PR-3003",
      status: "草稿",
      bom: [
        { id: "M-335", material: "压装弹簧", qty: "2", uom: "pcs", scrap: "1.5%" },
        { id: "M-612", material: "压装外壳", qty: "1", uom: "pcs", scrap: "0.6%" },
        { id: "M-661", material: "防护泡棉", qty: "1", uom: "pcs", scrap: "0.9%" },
      ],
      steps: [
        { sequence: 10, name: "外协收料", station: "OUT-01", equipment: "外协压装工装", qualityGate: "来料批次", sop: "SOP-OS-310", status: "待发布" },
        { sequence: 20, name: "压装首件", station: "OUT-02", equipment: "外协压装工装", qualityGate: "首件尺寸", sop: "SOP-OS-320", status: "待发布" },
        { sequence: 30, name: "成品复核", station: "QC-04", equipment: "量测工位", qualityGate: "QA 放行", sop: "SOP-OS-330", status: "待发布" },
      ],
    },
  ],
  kanbanBoards: [
    {
      id: "KB-OPS",
      name: "集团经营总览",
      audience: "COO / 工厂总经理",
      scope: "三工厂 · 17 产线",
      refreshRate: "60 秒",
      layout: "经营驾驶舱",
      owner: "运营管理部",
      status: "已发布",
      lastPublished: "今天 08:30",
      widgets: ["准交预测", "产线 OEE", "缺料风险", "质量红线", "成本差异", "异常关闭时长"],
    },
    {
      id: "KB-SHOP",
      name: "车间现场大屏",
      audience: "生产主管 / 班组长",
      scope: "华东一厂 · 灌装/包装/柔性线",
      refreshRate: "15 秒",
      layout: "投屏大屏",
      owner: "生产管理部",
      status: "变更中",
      lastPublished: "昨天 17:45",
      widgets: ["今日派工", "工序进度", "设备告警", "节拍偏差", "待料工单", "现场事件流"],
    },
    {
      id: "KB-QA",
      name: "质量追溯看板",
      audience: "质量经理 / QA",
      scope: "批次 · 检验 · CAPA",
      refreshRate: "5 分钟",
      layout: "质量分析",
      owner: "质量管理部",
      status: "草稿",
      lastPublished: "未发布",
      widgets: ["偏差队列", "批次追溯", "首检通过率", "CAPA SLA", "客户投诉", "放行状态"],
    },
  ],
  equipmentAssets: [
    {
      id: "EQ-1001",
      name: "灌装旋盖机",
      line: "L1",
      plant: "华东一厂",
      status: "告警",
      health: 72,
      oee: 83,
      temperature: 68,
      vibration: 4.8,
      nextMaintenance: "今天 16:00",
      owner: "设备一组",
      sensors: ["温度", "扭矩", "振动", "电流"],
    },
    {
      id: "EQ-1002",
      name: "高速贴标机",
      line: "L2",
      plant: "华东一厂",
      status: "运行",
      health: 88,
      oee: 79,
      temperature: 54,
      vibration: 2.6,
      nextMaintenance: "明天 09:30",
      owner: "包装维修",
      sensors: ["位置", "速度", "视觉", "振动"],
    },
    {
      id: "EQ-1003",
      name: "ICT 测试台",
      line: "L3",
      plant: "华东一厂",
      status: "运行",
      health: 93,
      oee: 91,
      temperature: 47,
      vibration: 1.7,
      nextMaintenance: "周五 14:00",
      owner: "电子工程",
      sensors: ["电压", "治具", "测试结果", "温度"],
    },
    {
      id: "EQ-1004",
      name: "外协压装工装",
      line: "L4",
      plant: "华南二厂",
      status: "保养中",
      health: 66,
      oee: 70,
      temperature: 52,
      vibration: 3.4,
      nextMaintenance: "进行中",
      owner: "外协设备",
      sensors: ["压力", "行程", "节拍", "振动"],
    },
  ],
  orders: [
    {
      id: "WO-61872",
      customer: "海辰渠道",
      sku: "果味饮料 330ml",
      line: "L1",
      due: "今天 18:00",
      priority: "P0",
      status: "风险",
      progress: 72,
      blockers: ["L1 负载高", "M-884 库存偏低"],
    },
    {
      id: "WO-61891",
      customer: "长桥日化",
      sku: "洁净凝露 2L",
      line: "L2",
      due: "明天 10:30",
      priority: "P1",
      status: "阻塞",
      progress: 44,
      blockers: ["等待包材入库"],
    },
    {
      id: "WO-61904",
      customer: "明科电子",
      sku: "控制板 A7",
      line: "L3",
      due: "明天 16:00",
      priority: "P1",
      status: "正常",
      progress: 58,
      blockers: [],
    },
    {
      id: "WO-61928",
      customer: "北辰装备",
      sku: "压装套件 P9",
      line: "L4",
      due: "周五 12:00",
      priority: "P2",
      status: "正常",
      progress: 28,
      blockers: ["外协首件未确认"],
    },
  ],
  materials: [
    { id: "M-884", name: "铝塑包材", stock: 420, safeStock: 800, location: "WH-A-02", linkedOrders: ["WO-61872", "WO-61891"] },
    { id: "M-120", name: "食品级瓶坯", stock: 6200, safeStock: 4000, location: "WH-B-11", linkedOrders: ["WO-61872"] },
    { id: "M-774", name: "控制芯片", stock: 980, safeStock: 900, location: "WH-C-09", linkedOrders: ["WO-61904"] },
    { id: "M-335", name: "压装弹簧", stock: 260, safeStock: 360, location: "WH-D-04", linkedOrders: ["WO-61928"] },
  ],
  qualityIssues: [
    { id: "Q-2031", batch: "GM-2031", severity: "高", source: "首件检验", owner: "质检组 A", status: "处理中", rootCause: "灌装扭矩波动超阈值" },
    { id: "Q-2037", batch: "GM-2037", severity: "中", source: "巡检", owner: "包装班组", status: "待处理", rootCause: "标签偏移 2.1mm" },
    { id: "Q-1984", batch: "GM-1984", severity: "低", source: "客户投诉", owner: "售后质量", status: "已关闭", rootCause: "运输外箱破损" },
  ],
  events: [
    { id: "E-1", time: "09:42", type: "生产", message: "L2 完成 WO-61891 首件确认，等待包材补齐" },
    { id: "E-2", time: "09:30", type: "库存", message: "M-884 到货 240 件，仍低于安全库存" },
    { id: "E-3", time: "09:18", type: "计划", message: "系统识别 L3 有 44% 可用产能，可承接 WO-61872" },
    { id: "E-4", time: "09:05", type: "质量", message: "Q-2031 进入偏差复核，关联批次 GM-2031" },
  ],
  recommendations: [
    {
      id: "R-1",
      severity: "高",
      title: "将 WO-61872 切换至柔性三线",
      body: "L1 当前负载 78%，L3 有空闲产能。切换后预计提前 6.5 小时交付，但需要同步更新首件确认任务。",
      impact: "准交率 +2.8%，换线损耗 -11%",
      accepted: false,
    },
    {
      id: "R-2",
      severity: "中",
      title: "触发 M-884 包材补货与替代料评估",
      body: "M-884 当前库存低于安全库存 380 件，影响两个高优先级工单。建议采购补货，同时评估 M-884B 替代。",
      impact: "缺料阻塞风险 -42%",
      accepted: false,
    },
    {
      id: "R-3",
      severity: "低",
      title: "复用华南二厂压装 SOP 模板",
      body: "WO-61928 的外协装配与历史工艺相似，可复用已验证 SOP 并减少工程确认时间。",
      impact: "工程等待 -3.2 小时",
      accepted: false,
    },
  ],
  intelligenceInsights: [
    {
      id: "BI-1001",
      title: "WO-61872 准交率预测下滑",
      domain: "交付",
      severity: "高",
      metric: "准交预测",
      value: "91%",
      change: "-3.2%",
      source: "订单 + 产能 + 物料",
      linkedEntity: "WO-61872",
      recommendation: "将高优先级订单切换至 L3，并同步首件确认与质量复核。",
      owner: "计划主管",
      status: "待处理",
    },
    {
      id: "BI-1002",
      title: "M-884 包材低于安全库存",
      domain: "库存",
      severity: "高",
      metric: "缺料影响",
      value: "2 单",
      change: "+2",
      source: "WMS + MRP",
      linkedEntity: "M-884",
      recommendation: "创建补货申请，同时评估替代料 M-884B 对 WO-61891 的适配性。",
      owner: "物料计划",
      status: "待处理",
    },
    {
      id: "BI-1003",
      title: "外协压装工装健康分偏低",
      domain: "设备",
      severity: "中",
      metric: "设备健康",
      value: "66%",
      change: "-8%",
      source: "IoT + EAM",
      linkedEntity: "EQ-1004",
      recommendation: "完成点检保养，并把外协首件确认流程前置到班前会。",
      owner: "设备工程",
      status: "待处理",
    },
    {
      id: "BI-1004",
      title: "Q-2031 偏差处理超过质量 SLA",
      domain: "质量",
      severity: "中",
      metric: "偏差时长",
      value: "5.8h",
      change: "+1.2h",
      source: "QMS + 流程引擎",
      linkedEntity: "Q-2031",
      recommendation: "升级 QA 经理复核，并把扭矩波动样本挂入批次追溯链。",
      owner: "QA 经理",
      status: "待处理",
    },
  ],
  rules: [
    { id: "RULE-OTD", name: "准交风险预警", module: "计划", enabled: true, threshold: "交期 < 8h 且进度 < 80%" },
    { id: "RULE-STOCK", name: "安全库存预警", module: "库存", enabled: true, threshold: "库存 < 安全库存" },
    { id: "RULE-QA", name: "高等级偏差升级", module: "质量", enabled: true, threshold: "严重度 = 高 且 2h 未关闭" },
  ],
  integrations: [
    { id: "INT-ERP", name: "金蝶 ERP", type: "REST", status: "已连接", lastSync: "10 分钟前" },
    { id: "INT-PLM", name: "研发 PLM", type: "Webhook", status: "已连接", lastSync: "38 分钟前" },
    { id: "INT-WMS", name: "仓储 WMS", type: "Event", status: "告警", lastSync: "2 小时前" },
  ],
  implementationPhases: [
    { id: "IMP-0", name: "诊断与 ROI", owner: "售前顾问 + COO", time: "第 0 周", status: "已完成", detail: "确认首厂范围、关键指标、系统边界和试点产线。" },
    { id: "IMP-1", name: "蓝图与角色矩阵", owner: "实施顾问 + IT", time: "第 1 周", status: "进行中", detail: "沉淀流程蓝图、权限、主数据字典和接口清单。" },
    { id: "IMP-2", name: "主数据与工厂建模", owner: "IT + 生产/质量", time: "第 2 周", status: "待开始", detail: "导入物料、BOM、工艺路线、产线、设备、人员。" },
    { id: "IMP-3", name: "配置与集成", owner: "实施顾问 + IT", time: "第 3-5 周", status: "待开始", detail: "配置规则、表单、看板，联调 ERP/PLM/WMS/API。" },
    { id: "IMP-4", name: "试点产线", owner: "工厂总经理", time: "第 5-6 周", status: "待开始", detail: "真实工单跑通订单、物料、生产、质量和审计闭环。" },
    { id: "IMP-5", name: "上线与扩厂复制", owner: "客户成功", time: "第 7-8 周", status: "待开始", detail: "验收上线，沉淀模板并复制到更多产线与工厂。" },
  ],
  mobileTasks: [
    {
      id: "MOB-1",
      type: "报工",
      title: "L2 包装二线工序报工",
      target: "WO-61891",
      scanCode: "WO-61891",
      owner: "包装班组",
      status: "待执行",
      instruction: "扫码工单，确认本工序完工数量并回写排程进度。",
    },
    {
      id: "MOB-2",
      type: "发料",
      title: "M-884 包材备料发放",
      target: "M-884",
      scanCode: "WH-A-02/M-884",
      owner: "仓储一组",
      status: "待执行",
      instruction: "扫描库位与物料，向 WO-61872 发放 80 件包材。",
    },
    {
      id: "MOB-3",
      type: "质检",
      title: "Q-2037 标签偏移巡检确认",
      target: "Q-2037",
      scanCode: "GM-2037",
      owner: "质检组 A",
      status: "待执行",
      instruction: "扫码批次，确认复检结果并关闭低风险质量任务。",
    },
  ],
  industryTemplates: [
    {
      id: "TPL-FB",
      name: "食品饮料快消模板",
      industry: "食品饮料",
      fit: "批次追溯、灌装包装、保质期、包材齐套",
      modules: ["生产管理", "仓储管理", "质量管理", "批次追溯", "移动扫码"],
      roles: ["计划员", "包装班组", "质检员", "仓库员", "工厂总经理"],
      fields: ["批号", "保质期", "灌装线", "包材批次", "首件扭矩"],
      rollout: "4 周样板线，8 周复制到包装/灌装多产线",
      status: "已启用",
    },
    {
      id: "TPL-ELEC",
      name: "电子装配多工序模板",
      industry: "电子装配",
      fit: "序列号、工序防错、外协装配、测试记录",
      modules: ["工艺路线", "生产执行", "质量管理", "设备/测试", "开放集成"],
      roles: ["工程师", "测试员", "线长", "质量经理", "外协伙伴"],
      fields: ["SN", "测试工站", "治具编号", "返修原因", "外协批次"],
      rollout: "6 周打通 SMT/组装/测试，12 周覆盖外协",
      status: "可启用",
    },
    {
      id: "TPL-PHARMA",
      name: "医药日化合规模板",
      industry: "医药日化",
      fit: "电子批记录、偏差 CAPA、双人复核、审计追踪",
      modules: ["质量管理", "流程引擎", "批记录", "权限复核", "审计日志"],
      roles: ["QA", "QC", "生产主管", "仓库复核", "合规负责人"],
      fields: ["电子签名", "复核人", "偏差等级", "留样编号", "清场记录"],
      rollout: "8 周完成批记录闭环，后续扩展验证与留样",
      status: "可启用",
    },
  ],
  workflowInstances: [
    {
      id: "WF-1001",
      name: "生产变更审批",
      category: "生产管理",
      businessKey: "WO-61872",
      owner: "计划主管",
      sla: "2 小时",
      currentStep: 1,
      status: "进行中",
      steps: ["发起变更", "计划审核", "质量复核", "现场执行", "关闭归档"],
      route: "订单排程 -> 质量复核 -> 移动现场 -> 审计归档",
    },
    {
      id: "WF-1002",
      name: "质量 CAPA 闭环",
      category: "质量管理",
      businessKey: "Q-2031",
      owner: "QA 经理",
      sla: "8 小时",
      currentStep: 2,
      status: "进行中",
      steps: ["偏差登记", "根因分析", "CAPA 审核", "效果确认", "归档"],
      route: "质量闭环 -> 流程引擎 -> 批次追溯",
    },
    {
      id: "WF-1003",
      name: "采购申请审批",
      category: "物料采购",
      businessKey: "M-884",
      owner: "采购经理",
      sla: "4 小时",
      currentStep: 0,
      status: "待处理",
      steps: ["MRP 建议", "采购复核", "供应商确认", "到货承诺", "入库关闭"],
      route: "MRP -> 采购供应商 -> WMS 入库",
    },
  ],
};
